### ISSUE TITLE
[BUG] 'Fullscreen' renders with black background (even if Obsidian is in light mode)

### ISSUE THREAD

**Issue by avirosso** [gitcpy/diagram-zoom-drag#25]
'Fullscreen' renders with black background (even if Obsidian is in light mode). As a result, the mermaid arrows and borders aren't visible in fullscreen

Normal:

![normal](https://github.com/user-attachments/assets/84bab692-7f61-4e12-b115-2c0d3315f30b)

Fullscreen:

![fullscreen](https://github.com/user-attachments/assets/273a2034-a7f1-42a4-987c-1ca50d38062f)

**Comment by Ssentiago** [comment]
> 'Fullscreen' renders with black background (even if Obsidian is in light mode). As a result, the mermaid arrows and borders aren't visible in fullscreen
> 
> Normal:
> 
> ![normal](https://github.com/user-attachments/assets/84bab692-7f61-4e12-b115-2c0d3315f30b)
> 
> Fullscreen:
> 
> ![fullscreen](https://github.com/user-attachments/assets/273a2034-a7f1-42a4-987c-1ca50d38062f)
> 

Hey, thanks, I'll check it out. But it seems like I haven't made any changes related to fullscreen mode. It’s just the native browser method. If there's an issue, it might be on Obsidian's side, but I'll take a look and see what's wrong.

**Comment by Ssentiago** [comment]
Should be fixed. Will be in the next release
