### ISSUE TITLE
Hide the user interface when not in use?

### ISSUE THREAD

**Issue by notuntoward** [gitcpy/diagram-zoom-drag#26]
This plugin works well, but when I have a lot of diagrams, it greatly increases the page length, due to the whitespace added around each diagram by the user interface.  The user interface always appearing in every diagram also adds visual clutter, slightly detracting from readability.

So, I'd like it if the user interface were activated only by a hotkey or a context-menu item selected from a right click on the diagram.  Another possibility could be to activate the user interface when the mouse or cursor is on the image.

**Comment by Ssentiago** [comment]
> This plugin works well, but when I have a lot of diagrams, it greatly increases the page length, due to the whitespace added around each diagram by the user interface. The user interface always appearing in every diagram also adds visual clutter, slightly detracting from readability.
> 
> So, I'd like it if the user interface were activated only by a hotkey or a context-menu item selected from a right click on the diagram. Another possibility could be to activate the user interface when the mouse or cursor is on the image.

That's a good point, thanks for noticing that. I will definitely see what can be done about it.

**Comment by gitcpy** [comment]
Yes, good idea.

**Comment by gitcpy** [comment]
Is it neccessory to make a setting for default height? The user set the default height and only an 'eye' button or a 'fold' button left in container, which the diagram was zoomed in to fit in the container. When user click, the container unfold, and the diagram zoom out to fit in the container. Then the user interface display. How do you think about it?

**Comment by Ssentiago** [comment]
> Is it neccessory to make a setting for default height? The user set the default height and only an 'eye' button or a 'fold' button left in container, which the diagram was zoomed in to fit in the container. When user click, the container unfold, and the diagram zoom out to fit in the container. Then the user interface display. How do you think about it?

I have considered this issue before. As far as I remember, there were some problems with the placement of the content depending on the different heights. But I tested on a large chart.

**Comment by gitcpy** [comment]
> > Is it neccessory to make a setting for default height? The user set the default height and only an 'eye' button or a 'fold' button left in container, which the diagram was zoomed in to fit in the container. When user click, the container unfold, and the diagram zoom out to fit in the container. Then the user interface display. How do you think about it?
> 
> I have considered this issue before. As far as I remember, there were some problems with the placement of the content depending on the different heights. But I tested on a large chart.

Thanks! Keep your pace!

**Comment by Ssentiago** [comment]
Added and released. You can check it out and leave your review. Everything seems to be fine.

**Comment by notuntoward** [comment]
> Added and released. You can check it out. But everything seems to be fine.

I like that the UI is mostly hideable with `toggle-panel-visibility` but the command doesn't remove all of the UI, and doesn't remove any of the whitespace it adds, as far as I can tell.  Below is an example where I've clicked on the top diagram and then have run `toggle-panel-visibility` .

# Initial View
![image](https://github.com/user-attachments/assets/179097f0-b693-4eaa-ad8e-9d73ef13ff85)

# After Clicking on Top Diagram
![image](https://github.com/user-attachments/assets/b5f0b152-f593-4e82-9f0f-5d9cfabfbc4e)

# After Running  Toggle-Panel-Visibility
![image](https://github.com/user-attachments/assets/4c547261-b29d-46f6-864b-b0965020bada)

**Comment by Ssentiago** [comment]
> command doesn't remove all of the UI

Do you mean that fold button?

**Comment by Ssentiago** [comment]
> doesn't remove any of the whitespace it adds, as far as I can tell

I'll check out it

**Comment by gitcpy** [comment]
Or he just needs a way to shrink the whitespace.

**Comment by Ssentiago** [comment]
> > > doesn't remove any of the whitespace it adds, as far as I can tell
> > 
> > 
> > I'll check out it
> 
> I think he mean that when the panel hidden, the diagram should be fit in the container so that the whitespace would be fold only.

that is, if we delete the panels, then also delete the place that these panels occupied?

**Comment by gitcpy** [comment]
> > > > doesn't remove any of the whitespace it adds, as far as I can tell
> > > 
> > > 
> > > I'll check out it
> > 
> > 
> > I think he mean that when the panel hidden, the diagram should be fit in the container so that the whitespace would be fold only.
> 
> that is, if we delete the panels, then we also should delete the place that these panels occupied? this is the point?

Maybe not. For now, we should make it clear for the useful function.
1. Keep the diagram in the container. And make it fit in the container at anytime.
2. We need two settings: 1) a folded container height setting ; 2) an unfolded container height.
3. Obviously, if the width of the diagram less than the container, and the height of it less than the folded container height, just leave it. And make the height container fit to the diagram.
4. Or,  we  zoom it proportionally in the container.

That's the init view for the diagram.

And then, we just put the foldable button and eye button on the diagram. Or one more fullscreen button.

Now, the user have choices.

1. To watch the init diagram.
2. From 'Step 1', unfold it, larger than init diagram.
3. From 'Step 1', directly open the fullscreen view, and then you know what is the following.
4. At 'Step 1', the panel should hide. User could just zoom or drag in init view. Or go to 'Step 2', or go to 'Step 3'.
5. At 'Step 2' and 'Step 3', the panel works as it designed before.

I hope I describe clearly. 

If you have any question， just go on disscussion.

Thank you very much.
