### ISSUE TITLE
feat: make a  hot key for hiding panel.

### ISSUE THREAD

**Issue by gitcpy** [gitcpy/diagram-zoom-drag#28]
I suggest the setting, hide by pressing ctrl + M, should be a hot key to avoid conflict with that from other plugins, or we just leave the free for the users. How about that?

**Comment by Ssentiago** [comment]
> I suggest the setting, hide by pressing ctrl + M, should be a hot key to avoid conflict with that from other plugins, or we just leave the free for the users. How about that?

got it, will be added

**Comment by gitcpy** [comment]
Checked, work fine, please merge.
