### ISSUE TITLE
Re-write panels hiding behavior

### ISSUE THREAD

**Issue by Ssentiago** [gitcpy/diagram-zoom-drag#31]
> > > > doesn't remove any of the whitespace it adds, as far as I can tell
> > > 
> > > 
> > > I'll check out it
> > 
> > 
> > I think he mean that when the panel hidden, the diagram should be fit in the container so that the whitespace would be fold only.
> 
> that is, if we delete the panels, then we also should delete the place that these panels occupied? this is the point?

Maybe not 'delete'. We could make it work more properly. 
For now, we should make it clear for the useful function.
1. Keep the diagram in the container. And make it fit in the container at anytime.
2. We need two settings: 1) a folded container height setting ; 2) an unfolded container height.
3. Obviously, if the width of the diagram less than the container, and the height of it less than the folded container height, just leave it. And make the height container fit to the diagram.
4. Or,  we  zoom it proportionally in the container.

That's the init view for the diagram.

And then, we just put the foldable button and eye button on the diagram. Or one more fullscreen button.

Now, the user have choices.

1. To watch the init diagram. The panel should be hide, except the 3 buttons referred above. User could just zoom or drag in init view
2. From 'Step 1', unfold it, larger than init diagram.
3. From 'Step 1', directly open the fullscreen view, and then you know what is the following.
4. At 'Step 2' and 'Step 3', the panel works as it designed before.

I hope I describe clearly. 

If you have any question， just go on disscussion.

Thank you very much.

_Originally posted by @gitcpy in https://github.com/gitcpy/diagram-zoom-drag/issues/26#issuecomment-2405683079_

**Comment by gitcpy** [comment]
> * To watch the init diagram. The panel should be hide, except the 3 buttons referred above. User could just zoom or drag in init view
> * From 'Step 1', unfold it, larger than init diagram.
> * From 'Step 1', directly open the fullscreen view, and then you know what is the following.
> * At 'Step 2' and 'Step 3', the panel works as it designed before.

Let me correct and simplify:
No matter it is folded or unfolded, auto adjust the height container to the diagram.
1. When it is folded, on the diagram, the panel should be hide, and only two buttons: folding button and fullscreen button. 
User could zoom or drag here.
2. If the user want a larger diagram, just click the folding button. And the panel works as designed before.

 I hope it do not bring you much trouble.
 Thank you!

**Comment by gitcpy** [comment]
I think new design would shrink the whitespace, and the user would get better experiance.

**Comment by gitcpy** [comment]
Take it easy. The most important is it passed the official audit. Always keep you pace. Thank you.

**Comment by gitcpy** [comment]
The most features are implemented.
And some details to comfirm:
1. To fit in fold or unfold container? 
Now:
![1019-fold](https://github.com/user-attachments/assets/eace8a49-28df-4cb8-a7ab-8144bcfa7527)
![1019-unfold-container](https://github.com/user-attachments/assets/f93ab122-2c93-4579-bef4-e61e7879d55d)
Expected:
![1019-fold-fit](https://github.com/user-attachments/assets/babd90a0-3781-4938-b9c3-2037bd6b5d70)
![1019-unfold-container-fit](https://github.com/user-attachments/assets/7ed5e0a7-ed1a-48fd-8935-5b1836000eca)
2. Margin
You can see the margin between the diagram-container div and the mermaid div. Could it be wiped?
3. Size of diagram
If it is folded, the height is hard-coded, it make the fit-in diagram quite small. We discuss the height setting for folded or unfoleded state before. I don't fined the settings. Dont't you think  is it necessary? Or they are somewhere I didn't realize?

It is easier said than done. At least it  takes time.

Always thanks for what you do.

**Comment by Ssentiago** [comment]
I haven't done any new improvements yet. I was rewriting the codebase because I didn't like the way it looked. I will deal with these things in the future.

**Comment by Ssentiago** [comment]
do you answering to my question in PR? or just writing?

**Comment by gitcpy** [comment]
> do you answering to my question in PR? or just writing?

Yes, I rewrite my discussion here.

**Comment by gitcpy** [comment]
You could discussion the point you don't like, here. And I think we will get the general consensus. I hope I didn't bring you much trouble.

**Comment by Ssentiago** [comment]
> You could discussion the point you don't like, here. And I think we will get the general consensus. I hope I didn't bring you much trouble.

What are you talking about? There seems to be nothing to discuss

**Comment by Ssentiago** [comment]
What about PR, its working?

**Comment by gitcpy** [comment]
Alright, you said you don't like it, and then I think there are something we could try.
And if you think we should stop here.&nbsp;
OK. Thanks for all you did! Bless you!&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gitcpy/diagram-zoom-drag"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月20日(星期天) 凌晨2:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gitcpy/diagram-zoom-drag] Re-write panels hiding behavior (Issue #31)





  
You could discussion the point you don't like, here. And I think we will get the general consensus. I hope I didn't bring you much trouble.
  
What are you talking about? There seems to be nothing to discuss

**Comment by Ssentiago** [comment]
> Alright, you said you don't like it, and then I think there are something we could try. And if you think we should stop here.&nbsp; OK. Thanks for all you did! Bless you!&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gitcpy/diagram-zoom-drag" ***@***.***&gt;; 发送时间:&nbsp;2024年10月20日(星期天) 凌晨2:04 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [gitcpy/diagram-zoom-drag] Re-write panels hiding behavior (Issue #31) You could discussion the point you don't like, here. And I think we will get the general consensus. I hope I didn't bring you much trouble. What are you talking about? There seems to be nothing to discuss — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Man, can i merge PR?

**Comment by gitcpy** [comment]
OK.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年10月20日(星期天) 凌晨2:18
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gitcpy/diagram-zoom-drag] Re-write panels hiding behavior (Issue #31)














  
Alright, you said you don't like it, and then I think there are something we could try. And if you think we should stop here.&nbsp; OK. Thanks for all you did! Bless you!&nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "gitcpy/diagram-zoom-drag" @.&gt;; 发送时间:&nbsp;2024年10月20日(星期天) 凌晨2:04 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [gitcpy/diagram-zoom-drag] Re-write panels hiding behavior (Issue #31) You could discussion the point you don't like, here. And I think we will get the general consensus. I hope I didn't bring you much trouble. What are you talking about? There seems to be nothing to discuss — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: @.***&gt;
  
Man, can i merge PR? It is OK?

**Comment by Ssentiago** [comment]
Didn't forget about hiding behavior, I will check out this
