### ISSUE TITLE
Feat: Enhance to the Settings panel. Feat: Add option to go unless full screen under zoom drag-and-drop support

### ISSUE THREAD

**Issue by LincZero** [gitcpy/diagram-zoom-drag#36]
1. More characters are supported.
    - so the selector should use querySelector, I want to use a condition like '.classA.classB' or '.classA>.classB classC'，But the character limit prevents me from doing that.
    - Same with className, I can't use Spaces, `_`, `-` names
2. Selector switch. 
    - I may need to turn some options on or off temporarily, but I don't want to delete and add them frequently, which is very troublesome
3. I might just use the "full screen button"
    - I think this is the most useful feature of the plugin. I don't want my charts to be distorted and height increased by default because I need to support drag and drop behavior in non-full-screen situations. And there may be additional performance losses during this period.

My core needs are number three, and the rest are just suggestions.

**Comment by LincZero** [comment]
4. Zoom operations are allowed to be simplified from 'Ctrl+ Scroll' to 'scroll' only in full screen mode.
    - I personally focus more on the experience in full-screen mode, and the need for drag and drop and view in non-global mode is extremely low

**Comment by Ssentiago** [comment]
Good requests. I'll think about that, thanks

**Comment by Ssentiago** [comment]
> 1. More characters are supported. 
>    * so the selector should use querySelector, I want to use a condition like '.classA.classB' or '.classA>.classB classC'，But the character limit prevents me from doing that.
>    * Same with className, I can't use Spaces, `_``-`,  names
> 2. Selector switch. 
>    * I may need to turn some options on or off temporarily, but I don't want to delete and add them frequently, which is very troublesome
> 3. I might just use the "full screen button" 
>    * I think this is the most useful feature of the plugin. I don't want my charts to be distorted and height increased by default because I need to support drag and drop behavior in non-full-screen situations. And there may be additional performance losses during this period.
> 
> My core needs are number three, and the rest are just suggestions.

Hey! I checked this. But what do you mean by point 3? Do you mean that the diagram changes its state (position, zoom) in fullscreen mode, and it affects the diagram in simple mode when you switch off the fullscreen mode?

**Comment by Ssentiago** [comment]
Other points are done.

**Comment by LincZero** [comment]
thanks.

By default, my chart looks different after using the plugin. Two in particular: 
- the height will always be larger or smaller than my original chart size (height auto-fitting can be troublesome)
- the performance (when there are multiple charts on a single page, it always feels like it is caused by modifying more HTML structures and putting layers of HTML around some elements).

I wanted to provide an option to avoid "enclosing" the selected HTML by default, and instead simply add a button element in the HTML location that won't work until I click the button.

Necessity description：
1. In terms of the frequency of operations, I think the chart has many more non-operational scenarios than the chart has operational scenarios.
    So the price of pressing the button once more when you need to zoom and drag the chart, for a better experience when you don't need to manipulate the chart, I think it's worth it (can be made an option).
2. Still from the operating frequency analysis, if you need to drag and zoom, I think there is a high probability that it will be carried out in full-screen mode. Most of the time, I don't need to do graphical manipulation on a small local graph. Personally, I prefer to just use the "full screen" button
3. performance problem
    It's fine at first, but as you switch between tabs with charts multiple times, it may become more and more stuck.
    I think this may be the default, do more operations on the page caused by. Simply inserting a button next to the target div might ameliorate this problem.

**Comment by gitcpy** [comment]
@Ssentiago  
I think @LincZero means that He just want make less panels in the container. 
- He just needs a button to open the full screen, because he just operates the charts in fullscreen mode. 
- He wants to decrease the margin space.
- For 'distorted', I think we need a pic or more details to discribe and check how it happened. Is it caused by css or something else?
- For performance, this is important. But maybe it would be one thing to deal with later. After all, complete first, optimise second. 

@LincZero
- Do you have anyting to supplement? Just leave messges here.

Thanks all.

**Comment by Ssentiago** [comment]
> thanks.
> 
> By default, my chart looks different after using the plugin. Two in particular:
> 
> * the height will always be larger or smaller than my original chart size (height auto-fitting can be troublesome)
> * the performance (when there are multiple charts on a single page, it always feels like it is caused by modifying more HTML structures and putting layers of HTML around some elements).
> 
> I wanted to provide an option to avoid "enclosing" the selected HTML by default, and instead simply add a button element in the HTML location that won't work until I click the button.
> 
> Necessity description：
> 
> 1. In terms of the frequency of operations, I think the chart has many more non-operational scenarios than the chart has operational scenarios. So the price of pressing the button once more when you need to zoom and drag the chart, for a better experience when you don't need to manipulate the chart, I think it's worth it (can be made an option).
> 2. Still from the operating frequency analysis, if you need to drag and zoom, I think there is a high probability that it will be carried out in full-screen mode. Most of the time, I don't need to do graphical manipulation on a small local graph. Personally, I prefer to just use the "full screen" button
> 3. performance problem It's fine at first, but as you switch between tabs with charts multiple times, it may become more and more stuck. nk this may be the default, do more operations on the page caused by. Simply inserting a button next to the target div might ameliorate this problem.

Thank you, I understand what ideas you want to convey. I am working on them as part of all other changes.
